src/main/java/org/jenkinsci/plugins/durabletask/executors/OnceRetentionStrategy.java
[https://issues.jenkins-ci.org/browse/JENKINS-26380](JENKINS-26380)
Supersedes #1.
=> [JENKINS-26380] Terminate nodes correctly

src/main/java/org/jenkinsci/plugins/durabletask/executors/OnceRetentionStrategy.java
Complements https://github.com/jenkinsci/branch-api-plugin/pull/5. Either suffice to fix the problem, but better to have both.
@reviewbybees
=> Do not kill a one-shot slave merely because a flyweight task happened to run on it

src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java
If left uncorrected, I suspect this would prevent `bat` steps from being used in flows when the Jenkins master is on Unix.
@reviewbybees esp. @rsandell
=> Reverting an incorrect change from #7

src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java, src/test/java/org/jenkinsci/plugins/durabletask/WindowsBatchScriptTest.java
When writing workspace paths into the `jenkins-wrapper.bat` batch
script, percentage signs need to be escaped correctly. Otherwise
the batch script execution will silently fail when the workspace
path contains a percentage sign. This was encountered in a multi branch
workflow project.
=> [JENKINS-32701] Escape percentage signs in the jenkins-wrapper batch 

.gitignore, pom.xml
[JENKINS-34647](https://issues.jenkins-ci.org/browse/JENKINS-34647)
Migrate to 2.7 parent pom. Ignore Findbugs errors for now. 
@reviewbybees
=> [JENKINS-34647] Migrate to 2.x parent pom.

src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java
I have a reproducable tests case in a propratary implementation using this
code that is 100% reproducable.
The simple "`@echo off`" fixes the failing test for me.
It seems that in the case that the parent process has been killed (e.g.
the slave dies) then all though the script terminates successfully and the
wrapper terminates successfully (checked with process monitor) there is no
attempt to create the result file.
where the parent process has not been killed I never see this issue.
All I needed to do to fix the issue I was observing is add `@echo off` as
the first line of the wrapper script. Basically I believe as it is trying to
echo the commands to be run before running the commands and as there is no
longer anything consuming the wrappers input/output when echoing the
command it is …
=> [JENKINS-34150] Fixes my observed issue.

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java, src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/WindowsBatchScriptTest.java
[JENKINS-40734](https://issues.jenkins-ci.org/browse/JENKINS-40734)
@reviewbybees
=> [JENKINS-40734] Escape $ in environment variable values so it does not get expanded by Launcher

src/main/java/org/jenkinsci/plugins/durabletask/ProcessLiveness.java
Generally want to avoid `ProcStarter.join()` without a timeout, in case the process hangs for some reason.
@reviewbybees
=> Apply a reasonable timeout to ps commands

src/main/java/org/jenkinsci/plugins/durabletask/PowershellScript.java, src/main/resources/org/jenkinsci/plugins/durabletask/PowershellScript/help-script.html, src/test/java/org/jenkinsci/plugins/durabletask/PowershellScriptTest.java
This PR fixes an issue that I discovered while using the PowerShell step that causes Unicode characters to not be interpreted properly.  I've also added a new test that checks for proper interpretation of Unicode chars.
Example:
`node {
powershell 'Write-Output "Hellõ"'
}`
Before this fix:
> ﻿HellÃµ
After this fix:
> Hellõ
PowerShell by default adds a BOM when writing Unicode text out to a file.  This is a bug, and is meant to be fixed soon as per the RFC:
https://github.com/PowerShell/PowerShell-RFC/blob/master/2-Draft-Accepted/RFC0020-DefaultFileEncoding.md
=> Fixing issues with unicode characters in PowerShell

src/main/java/org/jenkinsci/plugins/durabletask/executors/ContinuedTask.java, src/test/java/org/jenkinsci/plugins/durabletask/executors/ContinuedTaskTest.java
Saw some presumably unrelated failures in #49:
```
java.lang.AssertionError: expected:<1> but was:<0>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at org.jenkinsci.plugins.durabletask.executors.ContinuedTaskTest$1.perform(ContinuedTaskTest.java:55)
```
@reviewbybees
=> Trying to diagnose some ContinuedTaskTest failures

pom.xml
#49 inadvertently switched the plugin to use Java 8 despite a baseline of 2.7.x, due to a decision in https://github.com/jenkinsci/plugin-pom/pull/83 which I think was dangerous.
@reviewbybees
=> Specify java.level=7

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/main/java/org/jenkinsci/plugins/durabletask/Controller.java, src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/PowershellScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/WindowsBatchScriptTest.java
See discussion in [JENKINS-48300](https://issues.jenkins-ci.org/browse/JENKINS-48300). If we are going to return -1 (or -2) from `sh`, rather than an actual code, at least print some explanatory message.
@reviewbybees
=> [JENKINS-48300] Add an overload for exitStatus taking TaskListener

pom.xml, src/main/java/org/jenkinsci/plugins/durabletask/PowershellScript.java, src/main/resources/org/jenkinsci/plugins/durabletask/powershellHelper.ps1, src/test/java/org/jenkinsci/plugins/durabletask/PowershellScriptTest.java
Fixing several issues with powershell hanging and incorrect handling of exit codes
[JENKINS-46876](https://issues.jenkins-ci.org/browse/JENKINS-46876) [JENKINS-46508](https://issues.jenkins-ci.org/browse/JENKINS-46508)  [JENKINS-46496](https://issues.jenkins-ci.org/browse/JENKINS-46496)  [JENKINS-48057](https://issues.jenkins-ci.org/browse/JENKINS-48057)  [JENKINS-47797 ](https://issues.jenkins-ci.org/browse/JENKINS-47797 )
=> Fixed JENKINS-46876, JENKINS-46508, JENKINS-46496, JENKINS-48057, and JENKINS-47797

src/main/java/org/jenkinsci/plugins/durabletask/executors/OnceRetentionStrategy.java
Unrelated simplification pulled out of #29.
@reviewbybees
=> Using simpler Queue.withLock overload

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java, src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java
Superior version of https://github.com/jenkinsci/durable-task-plugin/pull/65
Proposed solution to error like this, encountered when statusCode file exists but is empty, potentially when created but not written to yet, or not written fully.  Was confirmed that previous version removed the errors with the "corrupt" status file content and greatly reduced failure rates.
> java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:592)
at java.lang.Integer.parseInt(Integer.java:615)
at org.jenkinsci.plugins.durabletask.FileMonitoringTask$FileMonitoringController.exitStatus(FileMonitoringTask.java:168)
> Caused: java.io.IOException: corrupted content in $SOMEPLACE 
> at …
=> Better fix to [JENKINS-25519] -- avoid errors when trying to read exitStatus from durable task before finished writing

src/main/java/org/jenkinsci/plugins/durabletask/PowershellScript.java, src/test/java/org/jenkinsci/plugins/durabletask/PowershellScriptTest.java
PowerShell output consists of 6 separate streams (success, error, warning, debug, verbose, and information), but only the success stream is conventionally considered to be stdout. The usage of returnStdout option of the PowerShell pipeline step should disregard all streams except the success stream to be consistent with other pipeline steps (bat, sh, etc.)
This PR prevents the warning, debug, verbose, or information streams from polluting stdout.
Caveats:
Normally in PowerShell when you use one of the various Write-* cmdlets, such as Write-Verbose or Write-Warning, the stream designation is prepended to the output. For example:
`Write-Verbose "This is some verbose output"`
Would yield:
> VERBOSE: This is some verbose output
There is a known issue when you invoke a PowerShell script and …
=> [Fixed JENKINS-49754] - Prevent PowerShell stdout pollution when using returnStdout

src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java
Should fix a regression [JENKINS-50025](https://issues.jenkins-ci.org/browse/JENKINS-50025) introduced in #66 -- a subtle issue that may revolve around a quirk of path handling in Windows. 
This triggers symptoms matching [JENKINS-34150](https://issues.jenkins-ci.org/browse/JENKINS-34150).  
After an hour of investigation with the user (results noted in ticket) and without an ability to easily reproduce the issue, **I am backing out the previous change to the BatchScriptDurableTask.**  
Other components of #66 (the zero-length file check) should adequately ensure Windows coverage for [JENKINS-25519](https://issues.jenkins-ci.org/browse/JENKINS-25519), and I'd rather go back to a known-good version than risk a second regression.  This version was tested with the user and confirmed to work …
=> [JENKINS-TBD] Fix hung Batch steps

src/main/java/org/jenkinsci/plugins/durabletask/PowershellScript.java, src/main/resources/org/jenkinsci/plugins/durabletask/powershellHelper.ps1, src/test/java/org/jenkinsci/plugins/durabletask/PowershellScriptTest.java
This PR fixes issues with backwards compatibility of error handling and error propagation, and ensures that non-fatal errors do not erroneously fail a job while also ensuring that $ErrorActionPreference is honored. The previous logic of relying on the $Error automatic variable is incorrect because it disregards the value of $ErrorActionPreference.
=> [Fixed JENKINS-50029] Fix issues with PowerShell error handling

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java
To the extent that I follow the analyses in [JENKINS-50892](https://issues.jenkins-ci.org/browse/JENKINS-50892) and [JENKINS-46283](https://issues.jenkins-ci.org/browse/JENKINS-46283) I suspect this will fix the problem. Something is still fishy—under some circumstances, something is killing the main wrapper process (the one whose `pid` is recorded here) and I do not know why or how to reproduce that.
Thanks to [this tip](https://stackoverflow.com/a/14880926/12916) for the liveness checking trick. Someone with a Mac ought to check that this works on OS X.
Note that superficially this looks to restore some stuff I deleted in #49. The difference here is that the PID checks are being done in an external process (so, no problems with JNA), and from a process in the same kernel namespace (so, …
=> [JENKINS-50892] Ensure the toucher process exits if the main wrapper process is killed

src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
See [JENKINS-37575](https://issues.jenkins-ci.org/browse/JENKINS-37575) where there is information to reproduce. This is dead code as of #60 + https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/63 but may as well fix the bug so long as the old code path can be run at least with a kill switch.
=> [JENKINS-37575] Keep track of how much content has been copied by writeLog even if the callable is interrupted

src/main/java/org/jenkinsci/plugins/durabletask/PowershellScript.java, src/test/java/org/jenkinsci/plugins/durabletask/PowershellScriptTest.java
This PR simplifies the wrapper that calls PowerShell to make it uniform across all supported PowerShell versions. This fixes an issue which prevents certain PowerShell output objects from being piped to disk, namely objects produced via Format-* cmdlets.
=> [Fixed JENKINS-50840] Simplifying PowerShell execution

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/test/java/org/jenkinsci/plugins/durabletask/AlpineFixture.java, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java, src/test/resources/org/jenkinsci/plugins/durabletask/AlpineFixture/Dockerfile
See [JENKINS-52847](https://issues.jenkins-ci.org/browse/JENKINS-52847) and  https://github.com/jenkinsci/durable-task-plugin/pull/75#discussion_r206994271.
Some implementations of `ps` don't support the `-p` option, but we can work around that by passing a more complicated regex to `grep`.
I manually tested the change on OS X and Alpine Linux to make sure it works on both platforms.
=> [JENKINS-52847] Avoid using -p to support basic implementations of ps

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/SlimFixture.java, src/test/resources/org/jenkinsci/plugins/durabletask/SlimFixture/Dockerfile
[JENKINS-52881](https://issues.jenkins-ci.org/browse/JENKINS-52881)
Amends #75 + #77, which do not work when the system `ps` fails to support even the most basic standard options (apparently there are a lot of nonstandard forks out there), or does not exist at all. Use procfs when that is available (which should also be a bit more efficient); if not; the JENKINS-50892 fix is just skipped. (I guess—we never managed to write a test case for that bug.)
=> [JENKINS-52881] Avoid use of ps

pom.xml, src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/main/java/org/jenkinsci/plugins/durabletask/Controller.java, src/main/java/org/jenkinsci/plugins/durabletask/DurableTask.java, src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java, src/main/java/org/jenkinsci/plugins/durabletask/Handler.java, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/EncodingTest.java
[JENKINS-52165](https://issues.jenkins-ci.org/browse/JENKINS-52165) Just the minimum changes pulled out of #29 to enable push rather than pull logging from durable tasks.
=> [JENKINS-52165] Controller.watch API

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/main/java/org/jenkinsci/plugins/durabletask/PowershellScript.java, src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java
There is no compelling reason to print these messages for every `sh` etc. step. The working directory is generally obvious from the script, and there is no other new information since the overall log or Blue Ocean or whatever indicates the nature of the step being run. I am not really sure why I ever added this message to begin with.
=> Removing noise from start of step

src/main/java/org/jenkinsci/plugins/durabletask/executors/OnceRetentionStrategy.java
Based on https://ci.jenkins.io/job/Infra/job/deprecated-usage-in-plugins/job/master/lastSuccessfulBuild/artifact/output/usage-by-plugin.html
=> Don't use deprecated TimeUnit2 anymore

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java
https://issues.jenkins-ci.org/browse/JENKINS-50902
Current implementation has several limitations:
- Does not support executable paths relative to `$PATH` variable as Shell step does, therefore making it hard for pipeline and freestyle to coexist.
- Reduces portability as the shebang expects absolute path making it hard for windows and unix nodes to coexist.
- Shebang does support interpreters with whitespace in its name, though that is a trivial one.
=> [JENKINS-50902] Do not rely on shebang for sh invocation

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/SlimFixture.java
Just because the container running the Jenkins agent has `/bin/sh` does not mean the container running the actual process will. For that matter, the remote callable does not even check—it just blindly returns `/bin/sh` on non-Windows platforms. Useless.
May conflict with #92, though that retains the shell launcher as a fallback.
See https://github.com/jenkinsci/kubernetes-plugin/pull/490 for integration test.
=> Shell.DescriptorImpl.getShellOrDefault is not reliable in the presence of LauncherDecorator

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java
[JENKINS-58290](https://issues.jenkins-ci.org/browse/JENKINS-58290)
~Alternative to #97: regardless of the `Proc` implementation~ ~Call `Proc.join` after launch~ Make sure we use `&` to launch the wrapper process as a background process. I would hope (but have not yet checked) that #92 also passes the same test (CC @car-roll).
~To my surprise, this does _not_ solve https://github.com/jenkinsci/kubernetes-plugin/pull/522. While `ContainerExecProc.join` calls `close` at the end, `join` never completes, despite the attempt at backgrounding, and so the WebSocket remains open. So there is something fishy going on which I have not identified.~ Seems that https://github.com/moby/moby/issues/33039#issuecomment-353250651 is key.
=> [JENKINS-58290] Run wrapper process in the background

src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/EncodingTest.java
A problem for some used of PCT:
```
java.io.IOException: Cannot run program "docker": error=2, No such file or directory
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at hudson.Proc$LocalProc.<init>(Proc.java:250)
at hudson.Proc$LocalProc.<init>(Proc.java:219)
at hudson.Launcher$LocalLauncher.launch(Launcher.java:937)
at hudson.Launcher$ProcStarter.start(Launcher.java:455)
at hudson.Launcher$ProcStarter.join(Launcher.java:466)
at org.jenkinsci.plugins.durabletask.BourneShellScriptTest.unixAndDocker(BourneShellScriptTest.java:82)
at …
Caused by: java.io.IOException: error=2, No such file or directory
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
at java.lang.ProcessImpl.start(ProcessImpl.java:134)
at …
```
=> Do not fail tests when run on a machine without Docker installed

Jenkinsfile, pom.xml, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/EncodingTest.java
https://github.com/jenkinsci/ssh-slaves-plugin/pull/114 was incompatible, so this plugin failed in `plugin-compat-tester`.
=> Update to the newest ssh-slaves version

src/main/java/org/jenkinsci/plugins/durabletask/PowershellScript.java, src/main/resources/org/jenkinsci/plugins/durabletask/PowershellScript/config.jelly, src/test/java/org/jenkinsci/plugins/durabletask/PowerShellCoreFixture.java, src/test/java/org/jenkinsci/plugins/durabletask/PowerShellCoreScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/PowershellScriptTest.java, src/test/resources/org/jenkinsci/plugins/durabletask/PowerShellCoreFixture/Dockerfile
Upstream of https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/122
added docker fixture test for `pwsh`.
This should allow us to create a `pwsh` step in `workflow-durable-task-step`
resolves #55 
resolves #73 
resolves #88
=> Allow setting pwsh as powershell executable

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java
Disabling binary wrapper that was introduced in v1.31 by default. 
Added system property `org.jenkinsci.plugins.durabletask.BourneShellScript.FORCE_BINARY_WRAPPER` to enable the binary. 
#114 will be used to address the bugs.
=> [JENKINS-59903] [JENKINS-59907] Disable golang binary as default

CHANGELOG.md, README.md, pom.xml
Unable to update wiki changelog since it is now read only.
Followed steps [here](https://jenkins.io/blog/2019/10/21/plugin-docs-on-github/) to migrate the wiki to github for documentation-as-code.
=> Migrate wiki changelog to github documentation as code

src/main/go/org/jenkinsci/plugins/durabletask/rebuild.sh, src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java
This PR is attempting to resolve the issues outlined in JENKINS-59903 and JENKINS-59907.
In 59903, the issue occurs when a docker-based agent does not have access to the jenkins caching directory. This prevents the  binary from  ever being copied over to the agent. To fix this, whenever there is no access to the  cache directory, caching will be disabled for the agent and the binary will be copied over to the agent's control directory for every shell execution.
In 59907, the binary is attempting to launch on non-x86 architectures. This  behavior  is currently blocked as the binary has  only been tested on  x86 machines. For  non-x86, non-*NIX architectures, the shell wrapper will be used.
=> [JENKINS-59903]  [JENKINS-59907]  caching with docker and uncommon architectures issues

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java, src/main/java/org/jenkinsci/plugins/durabletask/PowershellScript.java, src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java
See [JENKINS-60960](https://issues.jenkins-ci.org/browse/JENKINS-60960).
First commit makes the `BourneShellScriptTest.smokeTest()` fail, by detecting that some `UNIXProcess$ProcessPipeInputStream` are retained by the agent's `ExportTable`.
Second commit fixes this issue, by ensuring these streams (which are not used otherwise) get closed once the controller process has exited.  Not sure if it qualifies as a `durable-task` bugfix, or as a core/remoting bug workaround in `durable-task`, but anyway, it's still an improvement :)
With this patch, if one looks at the agent's `ExportTable` after using `BourneShellScript` (for instance at the end of the `smokeTest`), the stdout and stderr `UNIXProcess$ProcessPipeInputStream` objects from the controller process can be found in the …
=> [JENKINS-60960] fix/workaround memory leak on agent

Jenkinsfile, pom.xml, src/main/go/org/jenkinsci/plugins/durabletask/generate-binaries.sh, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/EncodingTest.java, src/test/java/org/jenkinsci/plugins/durabletask/PowerShellCoreScriptTest.java
Currently, when the `generate-binaries` script fails, it does not return a failure code and the entire build process will continue. This is especially important for the unit tests that are assuming the binary is present.
PCT will need to set `SKIP_BINARY_GENERATION=true` in the environment variables. This will skip the docker build, ignore the `binaryCaching` unit test as well as the `UBUNTU_NO_BINARY` test platform
=> make generate binaries script return error for failures

Jenkinsfile
I think that at some point the Windows agents on ci.jenkins.io switched to having Docker for Windows installed on them, which causes issues with tests that use `@ClassRule public static DockerRule` (e.g. `EncodingTest` here) because `DockerRule` just checks if `docker` is available and seems to be initialized before `@beforeClass` methods, but all of the standard images for use with `DockerRule` only work on Linux. Probably we need to update `docker-fixtures` to handle these kinds of issues automatically.
For now at least this should get the CI build passing here.
CC @daniel-beck
=> Use Windows ACI agents for CI build because they do not have Docker installed

Jenkinsfile, src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
See [JENKINS-55145](https://issues.jenkins-ci.org/browse/JENKINS-55145).
Before this PR, every call to `getOutput` would cause the following to be printed:
```
WARNING: Attempt to (de-)serialize anonymous class org.jenkinsci.plugins.durabletask.FileMonitoringTask$FileMonitoringController$1 in file:/var/lib/jenkins/plugins/durable-task/WEB-INF/lib/durable-task.jar;
see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
```
The anonymous class was only being serialized via remoting so we don't have to worry about maintaining serialization compatibility.
=> [JENKINS-55145] Convert anonymous class into named class to avoid serialization warnings

src/main/java/org/jenkinsci/plugins/durabletask/PowershellScript.java, src/main/resources/org/jenkinsci/plugins/durabletask/PowershellScript/config.jelly, src/test/java/org/jenkinsci/plugins/durabletask/PowershellScriptTest.java
Hey Team,
I would like to be able to load the PowerShell profile on the agent. This change is a step in that direction.
Please be kind. I ran the unit tests, but I'm not sure this will work, any ideas on how to test this properly?
Cheers, Mark
=> Add an option to load the PowerShell profile

src/main/java/org/jenkinsci/plugins/durabletask/PowershellScript.java, src/test/java/org/jenkinsci/plugins/durabletask/PowerShellCoreScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/PowershellScriptTest.java
- [ x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
https://issues.jenkins.io/browse/JENKINS-59529?jql=text%20~%20%22powershell%22
To fix this issue, I wrapped the invoked command in a `try { <user-supplied-command> } catch { throw }` to ensure that script/command not found errors, parameter not found and parameter validation errors will now fail the pipeline step.  This has been particularly painful when we have folks find - via the logs - steps that "pass" yet the log indicates the script never ran because someone typo'd the script name (or a parameter name).
=> Fix JENKINS-59529 - PowerShell command invocation errors will now fail the pipeline step

src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java, src/test/java/org/jenkinsci/plugins/durabletask/WindowsBatchScriptTest.java
Fixes the same issue with wrong (Unix) line endings in .bat scripts as in [JENKINS-7478](https://issues.jenkins.io/browse/JENKINS-7478) for pipeline `bat` step.
The idea for the fix of `WindowsBatchScript` is taken from https://github.com/jenkinsci/jenkins/pull/1370
=> Fix batch line endings to Windows (CRLF)

src/main/java/org/jenkinsci/plugins/durabletask/PowershellScript.java, src/test/java/org/jenkinsci/plugins/durabletask/PowerShellCoreScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/PowershellScriptTest.java
Fixes [Jenkins-65597](https://issues.jenkins.io/browse/JENKINS-65597) which was broken by my first attempt to fix [Jenkins-59529](https://issues.jenkins.io/browse/JENKINS-59529) via PR #131.  Unfortunately the test coverage for the PowerShell step did not cover the issue found in Jenkins-65597.  I've added two new tests to get coverage for that scenario plus ensuring a PowerShell step with a "parse error" will fail.
~First, I want to see the new tests fail first before checking in the code that should fix them (red / green approach).~
The fix removes all changes from powershellScript.ps1 - which resolves the issue with `[CmdletBinding()]` causing a parse error.  This is because certain statements like `[CmdletBinding()]` and `param()` must appear at the top of the script before any other …
=> Fix parse error on [CmdletBinding()] in PowerShell script and fix parse error not failing the step

src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java, src/test/java/org/jenkinsci/plugins/durabletask/WindowsBatchScriptTest.java
Fixed case when `exit /b` is used to return from `bat` step after an error produces SUCCESS result:
```groovy
node('windows') {
bat '''
cmd /c exit 42
exit /b
'''
}
```
```bat
Started by user Solovyev, Dmitriy
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on *********** in c:\******\jenkins\workspace\test-exit-b-bat-pipeline
[Pipeline] {
[Pipeline] bat
*************@*********** c:\******\jenkins\workspace\test-exit-b-bat-pipeline>cmd /c exit 42 
*************@*********** c:\******\jenkins\workspace\test-exit-b-bat-pipeline>exit /b 
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```
Such issue in "Freestyle" jobs has been fixed quite long ago in https://github.com/jenkinsci/jenkins/commit/12a83871398ed03a677 …
=> Properly handle batch scripts that call exit /b after an error

pom.xml
Bumping jenkins core to 2.277.1. The current version (2.150) cannot even load pipelines.
=> bump jenkins core to 2.277.1, parent pom, and dependencies

Jenkinsfile, pom.xml, src/main/java/org/jenkinsci/plugins/durabletask/AgentInfo.java, src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java, src/main/java/org/jenkinsci/plugins/durabletask/PowershellScript.java, src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/EncodingTest.java, src/test/java/org/jenkinsci/plugins/durabletask/PowerShellCoreScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/PowershellScriptTest.java, src/test/java/org/jenkinsci/plugins/durabletask/WindowsBatchScriptTest.java
Adding support for windows binary to launch powershell and batch scripts in a new process group.
Downstream of https://github.com/jenkinsci/lib-durable-task/pull/7
The following system properties must be added to the `jenkins.xml` file in the windows installation path
`-Dorg.jenkinsci.plugins.durabletask.WindowsBatchScript.FORCE_BINARY_WRAPPER=true`
`-Dorg.jenkinsci.plugins.durabletask.PowershellScript.FORCE_BINARY_WRAPPER=true`
=> [JENKINS-27617] Add support for windows binary

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java, src/main/java/org/jenkinsci/plugins/durabletask/PowershellScript.java, src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java
There is no particular security concern here, but some analyzers flag using MD5 as problematic. So, proposing to switch to SHA-256 and trying to keep backward compatibility on stoping tasks which cookie was hashed with MD5 (`JENKINS_SERVER_COOKIE`)
=> Switch from MD5 to SHA-256 algorithm to hash JENKINS_SERVER_COOKIE value

src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
Analogous to https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/81 but this time reverting a bit of complexity in #60. Together they seem to solve the `RestartableJenkinsRule` problems in https://github.com/jenkinsci/ant-plugin/pull/32. `Timer` should work fine in agent JVMs (it does not reference Jenkins model classes); the difference is for durable tasks (in watch mode) run on the master node: `Timer` gets properly shut down when Jenkins exits, and is thus safe for in-process restart tests. Again unlikely to have any meaningful impact in production.
=> Use the standard Timer rather than our own ScheduledExecutorService

src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
Exposes an error otherwise swallowed; see https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/212. If a `Callable` passed to `actAsync` throws an exception, and no one pays any attention to the resulting `Future`, it will never be reported. In this case the `Callable` just posted a task to an executor pool, so there was little reason to use `actAsync` to begin with; saves a tiny bit of round-trip time (even `actAsync` waits until the message has been delivered!) but makes debugging harder.
=> [JENKINS-68080] `FilePath.actAsync` is dangerous and not necessary in `FileMonitoringController.watch`

src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
Can just become noise especially in functional tests. (Noticed in https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/203 for example.)
=> Reducing log level for some repeated messages from `FileMonitoringTask`

src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
Noticed a nonfatal error in a functional test in `workflow-durable-task-step` while restarting a controller using an inbound agent in push mode (https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/323):
```
INFO	hudson.lifecycle.Lifecycle#onStatusUpdate: Jenkins stopped
jenkins.util.ErrorLoggingScheduledThreadPoolExecutor afterExecute
WARNING: failure in task not wrapped in SafeTimerTask
java.lang.NoClassDefFoundError: com/google/common/io/Files
at org.jenkinsci.plugins.durabletask.FileMonitoringTask$FileMonitoringController$StatusCheck.invoke(FileMonitoringTask.java:388)
at org.jenkinsci.plugins.durabletask.FileMonitoringTask$FileMonitoringController$StatusCheck.invoke(FileMonitoringTask.java:382)
at hudson.FilePath.act(FilePath.java:1192)
at …
```
=> Unnecessary use of Guava in `StatusCheck`

src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java, src/main/java/org/jenkinsci/plugins/durabletask/Handler.java
For https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/323. Temporarily copying utility from https://github.com/jenkinsci/remoting/pull/657.
=> [JENKINS-52165] Minor refinements for log push mode

pom.xml, src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java
Since the task recurs every 100ms, it seems unnecessary to read a file that we just wrote to disk.
=> More efficient `lastLocation` handling in watch mode

src/main/java/org/jenkinsci/plugins/durabletask/executors/OnceRetentionStrategy.java
Improved logging for why a cloud agent was terminated, and some routine stylistic cleanup.
=> Better logging in `OnceRetentionStrategy`

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java
Fixing [JENKINS-72436](https://issues.jenkins.io/browse/JENKINS-72436)
When running on z/OS always use the system's encoding  for reading file jenkins-result.txt. System's encoding is provided in system property ibm.system.encoding. 
No change in behavior for any other operating system. 
Successfully tested on a z/OS node the following pipeline:
```
pipeline {
agent{node('zOS-node')}
stages {
stage('example for bugreport')   {
steps {
sh(script:'''#!/bin/sh -e
echo "UTF-8 output" | iconv -f 1047 -t utf-8''', 
encoding:'UTF-8')
sh 'echo "native output"'
}
}
}
}
```
Test pipeline output:
```
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (example for bugreport)
[Pipeline] sh
UTF-8 output
[Pipeline] sh
+ echo native output 
native output
[Pipeline] } …
```
=> [JENKINS-72436] `sh` step on z/OS with `encoding` set to UTF-8 hangs when trying to read `jenkins-result.txt`

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java
https://issues.jenkins.io/browse/JENKINS-70874
```[tasklist]
```
=> [JENKINS-70874] Fix 'Text file busy' issue

pom.xml, src/main/java/org/jenkinsci/plugins/durabletask/executors/OnceRetentionStrategy.java, src/test/java/org/jenkinsci/plugins/durabletask/executors/OnceRetentionStrategyTest.java
Even though this is a "Once" Retention Strategy we expect a durable task to
be able to run to completion even if the connection is broken.  So we
relaunch the agent if the agent is offline and it is not done.
We are not forcing a reconnect, as this allows any existing connect
operation (which could be the first one, to continue running).
https://issues.jenkins.io/browse/JENKINS-69277
=> [JENKINS-69277] relaunch an agent if the connection is broken

src/test/java/org/jenkinsci/plugins/durabletask/CentOSFixture.java, src/test/resources/org/jenkinsci/plugins/durabletask/CentOSFixture/Dockerfile
Tests started failing recently in this plugin, e.g. https://github.com/jenkinsci/durable-task-plugin/pull/220/checks?check_run_id=28221800550 (#220). This seems to be due to a CentOS EOL https://github.com/docker-library/official-images/pull/17094. For purposes of these tests, we just care about general distro flavor, so using UBI is close enough.
Tested locally with:
```bash
mvnd test -Dtest='BourneShellScriptTest#*[3: CENTOS]'
```
=> Switch from CentOS to UBI

src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
Stumbled upon a TODO and make use of static method of remoting, which was integrated in [remoting PR657](https://github.com/jenkinsci/remoting/pull/657)
Only maven compile. Waiting if a test fails in CI.
=> Use method in remoting

src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java, src/test/java/org/jenkinsci/plugins/durabletask/WindowsBatchScriptTest.java
We have a job on a Windows machine which executes a Matlab project within a batch-file, and has actually a quite high error code of `3221225477`. We are using the binary wrapper, and so this quite high number gets written into the text file. The parsing fails with an `IOException` and the connection gets lost to the agent. I was first confused, but actually windows uses an unsigned int for the error codes, as documented [here](https://learn.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-seterrormode). I decided to set it to max integer, which is from my point of view better than throwing the exception, but I added a warning log message about it.
Added a unit test which reproduces the error and verifies that it is resolved like this.
=> Handle unsigned int errorcodes more gracefully in Windows Batch

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java
see https://issues.jenkins.io/browse/JENKINS-33708 discussion.
=> [JENKINS-33708] Do not call `nohup` for `sh` steps running on Windows

pom.xml
https://github.com/jenkinsci/durable-task-plugin/pull/222#pullrequestreview-2219707164 https://github.com/jenkinsci/durable-task-plugin/pull/223 Normally included in all plugins via `jenkins-test-harness`, and in this case also via `awaitility`.
=> No need for an explicit dep on Hamcrest

src/test/java/org/jenkinsci/plugins/durabletask/executors/OnceRetentionStrategyTest.java
Test introduced in #152 became unstable as of https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/463. Actually I am glad to be reminded of this old PR as it showed that until a year ago even an outbound cloud agent using the _recommended_ retention strategy could suffer from a permanent build hang as a result of a broken socket, suggesting that there are likely multiple flawed retention strategies floating around.
=> Flake in `OnceRetentionStrategyTest.deadConnectionsShouldReLaunched` after `DurableTaskStep` change

src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java, src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java, src/main/java/org/jenkinsci/plugins/durabletask/PowershellScript.java, src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java
No need to depend on a third-party library here when the Java Platform provides this functionality natively.
=> Remove usages of `StringUtils`

src/main/java/org/jenkinsci/plugins/durabletask/executors/OnceRetentionStrategy.java
`AbstractCloudSlave._terminate` is a potentially slow process (as suggested by the `IOException` / `InterruptedException` in its signature). For example `KubernetesSlave.deleteSlavePod` waits for a response from the API server, which might be overloaded and hanging. In the meantime the Jenkins queue lock is held (as of #2) which can cause everything else in the system to hang.
I tried to follow the justification in https://issues.jenkins.io/browse/JENKINS-26380 without success. The original issue was about a deadlock when `done` directly called `terminate`. That is addressed by backgrounding in `threadPoolForRemoting`. Then there was a lot of discussion about possible fixes in different places. The most relevant explanation seems to be
> builds being scheduled and then failing on a node …
=> Dropping `Queue` lock from `OnceRetentionStrategy.done`
