- src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java
- src/test/java/org/jenkinsci/plugins/durabletask/WindowsBatchScriptTest.java
[JENKINS-25678](https://issues.jenkins-ci.org/browse/JENKINS-25678)
@reviewbybees
> [JENKINS-25678] Space-in-path bug

- pom.xml
- src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java
- src/main/java/org/jenkinsci/plugins/durabletask/Controller.java
- src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
- src/main/java/org/jenkinsci/plugins/durabletask/ProcessLiveness.java
- src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java
- src/test/java/org/jenkinsci/plugins/durabletask/WindowsBatchScriptTest.java
> Better support for stop

- pom.xml
- src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java
- src/main/java/org/jenkinsci/plugins/durabletask/ContinuedTask.java
- src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java
And configured FindBugs for xml output so Jenkins can pick it up.
@reviewbybees
> Fixed FindBugs issues

- pom.xml
- src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java
- src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
- src/main/java/org/jenkinsci/plugins/durabletask/ProcessLiveness.java
- src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java
- src/main/java/org/jenkinsci/plugins/durabletask/executors/OnceRetentionStrategy.java
Allows for some code simplifications, and use of new queue locking (@stephenc). Anyway I cannot find any plugins depending on this API which are not already on 1.609.x.
@reviewbybees
> Updated to 1.609.x

- src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
[JENKINS-27152](https://issues.jenkins-ci.org/browse/JENKINS-27152)
@reviewbybees and @cruftex
> [JENKINS-27152] Ameliorate problem by using a predictable control directory name

- src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java
- src/test/java/org/jenkinsci/plugins/durabletask/WindowsBatchScriptTest.java
[JENKINS-27419](https://issues.jenkins-ci.org/browse/JENKINS-27419)
@reviewbybees esp. @jtnord
> [JENKINS-27419] Properly handle scripts that call exit without /b

- src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java
- src/main/java/org/jenkinsci/plugins/durabletask/ProcessLiveness.java
[JENKINS-32264](https://issues.jenkins-ci.org/browse/JENKINS-32264)
@reviewbybees
> [JENKINS-32264] Fix process liveness check for non-Linux platforms

- src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java
- src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java
[JENKINS-28400](https://issues.jenkins-ci.org/browse/JENKINS-28400)
@reviewbybees
> [JENKINS-28400] Better handle failure to start wrapper sh script

- src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java
- src/test/java/org/jenkinsci/plugins/durabletask/WindowsBatchScriptTest.java
[JENKINS-25678](https://issues.jenkins-ci.org/browse/JENKINS-25678) Amends #4.
Subsumes #17; [incremental diff](https://github.com/jglick/durable-task-plugin/compare/launch-failure-JENKINS-28400...win-space-in-path-JENKINS-25678)
@reviewbybees
> [JENKINS-25678] Space-in-path bug, revisited

- src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java
- src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
- src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java
- src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java
[JENKINS-27152](https://issues.jenkins-ci.org/browse/JENKINS-27152)
Supersedes #11.
@reviewbybees
> [JENKINS-27152] Store control files outside of the workspace

- src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java
- src/main/java/org/jenkinsci/plugins/durabletask/Controller.java
- src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
Used by https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/9.
@reviewbybees
> [JENKINS-31842] Define status of a Controller

- src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java
- src/main/java/org/jenkinsci/plugins/durabletask/Controller.java
- src/main/java/org/jenkinsci/plugins/durabletask/DurableTask.java
- src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
- src/main/java/org/jenkinsci/plugins/durabletask/WindowsBatchScript.java
- src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java
- src/test/java/org/jenkinsci/plugins/durabletask/WindowsBatchScriptTest.java
Infrastructure for [JENKINS-26133](https://issues.jenkins-ci.org/browse/JENKINS-26133).
@reviewbybees
> [JENKINS-26133] API for capturing output of a command

- src/main/java/org/jenkinsci/plugins/durabletask/BourneShellScript.java
[JENKINS-40225](https://issues.jenkins-ci.org/browse/JENKINS-40225)
Tested with 
- cygwin, node connected with ssh server
- git bash using, node connected with JNLP
> [JENKINS-40225] replace backslashes for windows shell

- Jenkinsfile
- pom.xml
- src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
- src/main/java/org/jenkinsci/plugins/durabletask/executors/OnceRetentionStrategy.java
Pending [INFRA-1168](https://issues.jenkins-ci.org/browse/INFRA-1168) and a successful build. Would be very helpful for Windows-specific changes like #39.
@reviewbybees
> Try a Jenkinsfile

- src/test/java/org/jenkinsci/plugins/durabletask/BourneShellScriptTest.java
Cf. [changelog](https://docs.docker.com/release-notes/docker-engine/#1130-2017-01-18). Follows up #49.
@reviewbybees
> Check that we are running a sufficiently recent version of Docker

- pom.xml
Picks up https://github.com/jenkinsci/docker-fixtures/pull/16.
@reviewbybees
> docker-fixtures 1.6

- src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
#84 is preferable but this should be easier to get merged quickly so I am starting here.
> Shut down watchService when Jenkins shuts down

- pom.xml
https://mvnrepository.com/artifact/org.jenkins-ci.plugins/plugin?repo=jenkins-releases
https://github.com/jenkinsci/plugin-pom/releases
https://github.com/jenkinsci/plugin-pom
> update org.jenkins-ci.plugins/plugin from 3.19 to 3.43

- README.md
Fix the link to the changelog in README
> correct the changelog link

- src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
Because it doesn't add anything.
> Drop AtomicReference on FileMonitoringTask.FileMonitoringController#writeLogCs

- src/main/java/org/jenkinsci/plugins/durabletask/FileMonitoringTask.java
- Remove utility function for tempDir and use implementation from core instead
> Use tempDir implementation from core

- CHANGELOG.md
Getting changelog ready for release once #121 is merged
> prepare changelog for 1.34 release

- CHANGELOG.md
I am planning on releasing the plugin today.
> Update changelog for 1.35

- CHANGELOG.md
> add 1.36 to CHANGELOG

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
- CHANGELOG.md
- README.md
> enable release-drafter

- .mvn/extensions.xml
https://github.com/jenkinsci/durable-task-plugin/pull/144#issuecomment-965826393
> Update Maven extension

- pom.xml
Bumps lib-durable-task to take in latest golang binaries
see https://github.com/jenkinsci/lib-durable-task/pull/63
> bump lib-durable-task

- src/test/resources/org/jenkinsci/plugins/durabletask/AlpineFixture/Dockerfile
Allow apk to upgrade openssh in Alpine Dockerfile to fix [JENKINS-72488](https://issues.jenkins.io/browse/JENKINS-72488)
At https://gitlab.alpinelinux.org/alpine/aports/-/issues/15606 user alice describes the issue and possible solutions:
> that's because that image already has openssh-client installed, but openssh was updated (so 9.5 doesn't exist anymore), and installing openssh (9.6), then adds a dependency on openssh-client (9.6) (because openssh depends on it), but an apk add won't upgrade, so it fails (since it doesn't want to upgrade to openssh-client 9.6). apk add -u openssh would work, or apk upgrade && apk add openssh to allow upgrades as part of the addition
Succesfully, ran docker build with the modified Dockerfile. This PR's github checks will show whether it works in CI …
> [JENKINS-72488] allow apk to upgrade openssh in Alpine Dockerfile
